---
# install and enable postgres

- name: Install postgresql-server
  package:
    name: "postgresql-server"
    state: latest
  register: postgresql-server_pkg_status

- name: start postgres
  service:
    name: postgresql.service
    state: started
  when:
    postgresql-server_pkg_status.rc == 0

- name: Enable postgres service
  service: 
    name: postgresql.service
    enabled: yes
